#!/bin/sh
#jinstall - Command line script to easily add new java directories to
#'alternatives'. This sets the java as default, and you can switch your
#default java with update-java-alternatives
#
#Copyright 2012 Bruce.Ingalls at gmail & Alin Andrei <webupd8@gmail.com>
#GPL v3 Affero license at http://www.gnu.org/
#Downloads & discussion at http://www.webupd8.org/
#Tested on Ubuntu Oneiric; should require few changes for other modern Unix systems
#Currently tested only with JDK, not JRE.
# Not fully internationalized, including japanese man pages
#
#Copyright 2020 Maksim Kaut <maksimkaut92@gmail.com>

set -e

VER='0.6alpha'

arch=amd64
dld=x64
SHA256SUM_TGZ="777a8d689e863275a647ae52cb30fd90022a3af268f34fc5b9867ce32f1b374e" #must be modified for each release

########Variables

JAVA_VERSION=8u251 #must be modified for each release jdk-8u5-linux-x64.tar.gz
J_DIR=jdk1.8.0_251 #must be modified for each release
FILENAME=jdk-${JAVA_VERSION}-linux-${dld}.tar.gz
PARTNER_URL=http://packages.mirohost.net/java/$FILENAME

for JAVA_VERSION_OLD in `seq 1 250`; do #must be modified for each release
  FILENAMES_OLD="jdk-8-ea-bin-b${JAVA_VERSION_OLD}-linux-${dld}-*.tar.gz $FILENAMES_OLD" #old name
  FILENAMES_OLD_N="jdk-8-fcs-bin-b${JAVA_VERSION_OLD}-linux-${dld}*.tar.gz $FILENAMES_OLD_N" #new name
  FILENAMES_OLD_NA="jdk-8-fcs-b${JAVA_VERSION_OLD}-linux-${dld}*.tar.gz $FILENAMES_OLD_NA" #arm
  FILENAMES_OLD_VER="jdk-8u${JAVA_VERSION_OLD2}-linux-${dld}*.tar.gz $FILENAMES_OLD_VER"
done

J_INSTALL_DIR=/usr/lib/jvm/java-8-oracle

. /usr/share/debconf/confmodule

db_get oracle-java8-installer/local
echo "$SHA256SUM_TGZ  $RET/$FILENAME" \
| sha256sum -c > /dev/null 2>&1 \
|| db_set oracle-java8-installer/local /var/cache/oracle-jdk8-installer

db_get oracle-java8-installer/local
echo "$SHA256SUM_TGZ  $RET/$FILENAME" \
| sha256sum -c > /dev/null 2>&1 \
|| db_set oracle-java8-installer/local /usr/lib/oracle-jdk8-installer-unpackdir

db_get oracle-java8-installer/local
echo "$SHA256SUM_TGZ  $RET/$FILENAME" \
| sha256sum -c > /dev/null 2>&1 \
|| db_reset oracle-java8-installer/local

while true; do
    db_input medium oracle-java8-installer/local || true
    db_go
    db_get oracle-java8-installer/local
    if [ -d "$RET" -a -f "$RET"/$FILENAME ]; then
		LOCAL="true"
		break;
    elif [ "x$RET" = "x" ]; then
		break;
    fi
    db_reset oracle-java8-installer/not_exist || true
    db_reset oracle-java8-installer/local || true
    db_text medium oracle-java8-installer/not_exist || true
    db_go
done

exit 0
